LINE_SEQUENCES = {
    "Yellow Line": [
        "Samaypur Badli", "Rohini Sector 18", "Haiderpur", "Jahangirpuri",
        "Adarsh Nagar", "Azadpur", "Model Town", "GTB Nagar",
        "Vishwa Vidyalaya", "Vidhan Sabha", "Civil Lines", "Kashmere Gate",
        "Chandni Chowk", "Chawri Bazar", "New Delhi", "Rajiv Chowk",
        "Patel Chowk", "Central Secretariat", "Udyog Bhawan",
        "Lok Kalyan Marg", "Jor Bagh", "INA", "AIIMS", "Green Park",
        "Hauz Khas", "Malviya Nagar", "Saket", "Qutab Minar", "Chhatarpur",
        "Sultanpur", "Ghitorni", "Arjan Garh", "Guru Dronacharya",
        "Sikandarpur", "MG Road", "IFFCO Chowk", "HUDA City Centre",
    ],
    "Blue Line": [
        "Dwarka Sector 21", "Dwarka Sector 8", "Dwarka Sector 9",
        "Dwarka Sector 10", "Dwarka Sector 11", "Dwarka Sector 12",
        "Dwarka Sector 13", "Dwarka Sector 14", "Dwarka", "Dwarka Mor",
        "Nawada", "Uttam Nagar West", "Uttam Nagar East", "Janakpuri West",
        "Janakpuri East", "Tilak Nagar", "Subhash Nagar", "Tagore Garden",
        "Rajouri Garden", "Ramesh Nagar", "Moti Nagar", "Kirti Nagar",
        "Shadipur", "Patel Nagar", "Rajendra Place", "Karol Bagh",
        "Jhandewalan", "Ramakrishna Ashram Marg", "Rajiv Chowk",
        "Barakhambha Road", "Mandi House", "Supreme Court", "Indraprastha",
        "Yamuna Bank", "Akshardham", "Mayur Vihar -I",
        "Mayur Vihar Extension", "New Ashok Nagar", "Noida Sector 15",
        "Noida Sector 16", "Noida Sector 18", "Botanical Garden",
        "Golf Course", "Noida City Centre", "Noida Sector 34",
        "Noida Sector 52", "Noida Sector 61", "Noida Sector 59",
        "Noida Sector 62", "Noida Electronic City",
    ],
    "Blue Line Branch": [
        "Yamuna Bank", "Laxmi Nagar", "Nirman Vihar", "Preet Vihar",
        "Karkarduma", "Anand Vihar ISBT", "Kaushambi", "Vaishali",
    ],
    "Red Line": [
        "Rithala", "Rohini West", "Rohini East", "Pitam Pura",
        "Kohat Enclave", "Netaji Subhash Place", "Keshav Puram",
        "Kanhaiya Nagar", "Inderlok", "Shastri Nagar", "Pratap Nagar",
        "Pul Bangash", "Tis Hazari", "Kashmere Gate", "Shastri Park",
        "Seelampur", "Welcome", "Shahdara", "Mansarovar Park", "Jhilmil",
        "Dilshad Garden", "Shaheed Nagar", "Raj Bagh", "Shyam Park",
        "Major Mohit Sharma", "Mohan Nagar", "Arthala", "Hindon",
        "Shaheed Sthal",
    ],
    "Violet Line": [
        "Kashmere Gate", "Lal Qila", "Jama Masjid", "Delhi Gate", "ITO",
        "Mandi House", "Janpath", "Central Secretariat", "Khan Market",
        "Jawaharlal Nehru Stadium", "Jangpura", "Lajpat Nagar",
        "Moolchand", "Kailash Colony", "Nehru Place", "Kalkaji Mandir",
        "Govind Puri", "Harkesh Nagar Okhla", "Jasola Apollo",
        "Sarita Vihar", "Mohan Estate", "Tughlakabad Station",
        "Badarpur Border", "Sarai", "NHPC Chowk", "Mewala Maharajpur",
        "Sector 28", "Badkhal Mor", "Old Faridabad", "Neelam Chowk Ajronda",
        "Bata Chowk", "Escorts Mujesar", "Sant Surdas (Sihi)",
        "Raja Nahar Singh",
    ],
    "Green Line": [
        "Brigadier Hoshiyar Singh", "Bahadurgarh City",
        "Pandit Shree Ram Sharma", "Tikri Border", "Tikri Kalan", "Ghevra",
        "Mundka Industrial Area", "Mundka", "Rajdhani Park", "Nangloi",
        "Nangloi Railway station", "Udyog Nagar", "Surajmal Stadium",
        "Peeragarhi", "Paschim Vihar West", "Paschim Vihar East", "Madipur",
        "Shivaji Park", "Punjabi Bagh", "Ashok Park Main", "Inderlok",
    ],
    "Green Line Branch": [
        "Ashok Park Main", "Satguru Ramsingh Marg", "Kirti Nagar",
    ],
    "Magenta Line": [
        "Janakpuri West", "Dabri Mor-Janakpuri South", "Dashrath Puri",
        "Palam", "Sadar Bazaar Cantonment", "Terminal 1-IGI Airport",
        "Shankar Vihar", "Vasant Vihar", "Munirka", "R.K.Puram", "IIT",
        "Hauz Khas", "Panchsheel Park", "Chirag Delhi", "Greater Kailash",
        "Nehru Enclave", "Kalkaji Mandir", "Okhla NSIC", "Sukhdev Vihar",
        "Jamia Millia Islamia", "Okhla Vihar", "Jasola Vihar Shaheen Bagh",
        "Kalindi Kunj", "Okhla Bird Sanctuary", "Botanical Garden",
    ],
    "Pink Line": [
        "Majlis Park", "Azadpur", "Shalimar Bagh", "Netaji Subhash Place",
        "Shakurpur", "Punjabi Bagh West", "ESI Hospital", "Rajouri Garden",
        "Mayapuri", "Naraina Vihar", "Delhi Cantonment",
        "Durgabai Deshmukh South Campus", "Sir Vishweshwaraiah Moti Bagh",
        "Bhikaji Cama Place", "Sarojini Nagar", "INA", "South Extension",
        "Lajpat Nagar", "Vinobapuri", "Ashram", "Hazrat Nizamuddin",
        "Mayur Vihar Pocket I", "Trilokpuri Sanjay Lake",
        "East Vinod Nagar - Mayur Vihar-II", "Mandawali - West Vinod Nagar",
        "IP Extension", "Anand Vihar ISBT", "Karkarduma", "Karkarduma Court",
        "Krishna Nagar", "East Azad Nagar", "Welcome", "Jaffrabad",
        "Maujpur-Babarpur", "Gokulpuri", "Johari Enclave", "Shiv Vihar",
    ],
    "Orange Line": [
        "New Delhi", "Shivaji Stadium", "Dhaula Kuan", "Delhi Aerocity",
        "Indira Gandhi International Airport", "Dwarka Sector 21",
    ],
    "Grey Line": ["Dwarka", "Nangli", "Najafgarh"],
}

ALIASES = {
    "Blue Line branch": "Blue Line Branch",
    "Green Line branch": "Green Line Branch",
    "Peeragarhi": "Peera Garhi",
    "Surajmal Stadium": "Maharaja Surajmal Stadium",
    "East Vinod Nagar - Mayur Vihar-II": "East Vinod Nagar - Mayur Vihar-II",
    "South Extension": "South",
    "IIT": "IIT Delhi",
    "Millennium City Centre Gurugram": "HUDA City Centre",
    "Vishwavidyalaya": "Vishwa Vidyalaya",
}
