INTERCHANGE_STATIONS = {
    "Rajiv Chowk",
    "Kashmere Gate",
    "Mandi House",
    "Central Secretariat",
    "Hauz Khas",
    "Janakpuri West",
    "Kalkaji Mandir",
    "Botanical Garden",
    "INA",
    "Lajpat Nagar",
    "Azadpur",
    "Netaji Subhash Place",
    "Rajouri Garden",
    "Anand Vihar ISBT",
    "Welcome",
    "Kirti Nagar",
    "Dwarka Sector 21",
    "Yamuna Bank",
    "Inderlok",
}

BUSINESS_STATIONS = {
    "Rajiv Chowk",
    "New Delhi",
    "Central Secretariat",
    "Mandi House",
    "Noida Sector 16",
    "Noida Sector 18",
    "Hauz Khas",
    "Lajpat Nagar",
    "Karol Bagh",
    "Kashmere Gate",
    "Botanical Garden",
    "Sikandarpur",
    "IFFCO Chowk",
    "MG Road",
    "Delhi Aerocity",
}
